# Generated by Django 3.2 on 2021-04-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id_vendedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
