# Generated by Django 3.2 on 2021-05-06 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores_cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.cidades')),
                ('cod_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedores')),
            ],
        ),
    ]
